// This file was generated by Prisma, and assumes you run Prisma commands using `bun --bun run prisma [command]`.
import dotenv from "dotenv";
import path from "path";
import { defineConfig, env } from "prisma/config";

dotenv.config({
  path: path.resolve(process.cwd(), "../../.env")
});

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "bun run prisma/seed.ts"
  },
  datasource: {
    url: env("DATABASE_URL")
  }
});
